export { default as Layout } from './Layout/Layout.jsx'

export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Home } from './Home/Home.jsx'
export { default as Teams } from './Teams/Teams.jsx'
export { default as Events } from './Events/Events.jsx'
export { default as About } from './About/About.jsx'
export { default as Button } from './Button/Button.jsx'
export { default as Title } from './Title/Title.jsx'
export { default as Terminal } from './Terminal/Terminal.jsx'
export { default as FAQs } from './FAQs/FAQs.jsx'
export { default as Forms } from './Forms/Forms.jsx'
export { default as Footer } from './Footer/Footer.jsx'
export { default as WhatPeopleThinkAboutUS } from './WhatPeopleThinkAboutUs/WhatPeopleThinkAboutUS.jsx'
export { default as NotFound } from './NotFound/NotFound.jsx'

export { default as RegisterForm } from './Form/RegisterForm.jsx'
export { default as AlumniNetwork } from './AlumniNetwork/AlumniNetwork.jsx'
export { default as Three } from './ThreeJS/Three.jsx'
export { default as AlumniMenu } from './AlumniDetail/AlumniMenu.jsx'
export { default as AchievementsForm } from './AchievementsForm/AchievementsForm.jsx'

export { default as Achievements } from './Achievements/Achievements.jsx'
export { default as SideBar } from './SideNavigationBar/SideBar.jsx'
