const User = require('../models/userModel');
const { sendEmail } = require('../utils/emailUtils');
const { personalizedBatchTemplate } = require('../utils/emailTemplates');

function getProgramDuration(prefix) {
    if (prefix === 'U') return 4;
    if (prefix === 'P') return 2;
    if (prefix === 'D' || prefix === 'I') return 5;
    return null;
}

function getAdmissionYear(admissionNumber) {
    const match = admissionNumber.match(/^([UPDI])(\d{2})/i);
    if (!match) return null;
    const year = parseInt(match[2], 10);
    return year >= 0 && year <= 99 ? 2000 + year : null;
}

exports.markAlumniAutomation = async (req, res) => {
    try {
        const users = await User.find({ isAlumni: { $ne: true } });
        const now = new Date();
        const currentYear = now.getFullYear();
        const currentMonth = now.getMonth();

        let markedCount = 0;

        for (const user of users) {
            const admissionNumber = user.admissionNumber;
            if (!admissionNumber) continue;

            const prefix = admissionNumber[0].toUpperCase();
            const duration = getProgramDuration(prefix);
            const admissionYear = getAdmissionYear(admissionNumber);

            if (!duration || !admissionYear) continue;

            const alumniYear = admissionYear + duration;
            const isAlumni = (currentYear > alumniYear) ||
                (currentYear === alumniYear && currentMonth >= 5);

            if (isAlumni) {
                user.isAlumni = true;
                user.isVerified = true;
                await user.save();
                markedCount++;
            }
        }

        // Send report email using the email utility
        const reportContent = `
            <div style="font-family: Arial, sans-serif; margin: 20px;">
                <h2>Alumni Marking Automation Report</h2>
                <p><strong>Users marked as alumni:</strong> ${markedCount}</p>
                <p><strong>Timestamp:</strong> ${new Date().toISOString()}</p>
                <p>This is an automated report generated by the NEXUS system.</p>
            </div>
        `;

        // Use the email utility instead of direct transporter
        await sendEmail({
            to: process.env.EMAIL_ID,
            subject: 'Alumni Marking Automation Report',
            html: personalizedBatchTemplate('Admin', reportContent)
        });

        res.json({ success: true, markedCount });
    } catch (err) {
        console.error("Alumni automation error:", err);
        res.status(500).json({ success: false, error: err.message });
    }
};
